# Generated by Django 5.2.1 on 2025-05-28 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
                (
                    "enrollment_number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                10, "The enrollment_number must contain 10 characters"
                            )
                        ],
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=150,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                10, "The password must contain at least 10 characters"
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
