# Generated by Django 5.2.1 on 2025-06-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_remove_task_is_completed_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completion_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
